apiVersion: v1
kind: Service
metadata:
  name: kafka-svc
spec:
  selector:
    app: stock_analyser
  clusterIP: None
  ports:
  - name: broker
    port: 9092
    targetPort: 9092
  - name: controller
    port: 9093
    targetPort: 9093
  - name: external
    port: 29092
    targetPort: 29092
  - name: postgresdb
    port: 5432
    targetPort: 5432
  - name: debezium
    port: 8083
    targetPort: 8083
  
